TODO instructions improvement
c-guntur/java-katas pull request #18
Opened 2019-10-07 18:58 UTC by faisal6621

At places the `TODO` instruction asks for replacing a value which is not
exactly there.

Improvement in `TestSolution1OptionalCreationAndFetchingValues.java`:
from the `@apiNote` of `Optional.get()`, the preferred alternative is
`Optional.orElseThrow()`.

2019-10-13 13:32 UTC, c-guntur commented
Thank you for the PR and apologies for the delay in actioning. Reviewing today.

2019-10-13 13:42 UTC, c-guntur commented on java-optional/src/solutions/java/none/cvg/optional/TestSolution1OptionalCreationAndFetchingValues.java
> -         *  Check API: java.util.Optional.isPresent()
Good catch!

This comment should read: "Check API: java.util.Optional.get()".

We have not yet introduced the orElseThrow method at this point. 

The solutions in the kata need not be the most optimal, but are designed to teach concepts as people start learning. The second exercise (Test2**.java) goes into conditionals.

2019-10-13 13:42 UTC, c-guntur commented on java-optional/src/solutions/java/none/cvg/optional/TestSolution1OptionalCreationAndFetchingValues.java
> -                    anotherOptionalInteger.get(),
This should remain "get()" and not "orElseThrow()", since the latter has not yet been introduced.

2019-10-13 13:44 UTC, c-guntur commented on java-optional/src/test/java/none/cvg/optional/TestKata1OptionalCreationAndFetchingValues.java
> -         *  Replace the "false" to check that the Optional has a non-null value.
Good catch !

2019-10-13 13:47 UTC, c-guntur commented on java-optional/src/test/java/none/cvg/optional/TestKata1OptionalCreationAndFetchingValues.java
> +         *  Replace the "11" to get the Optional has a null value.
Good catch ! Though this should be 10 and not 11. the inner "assertNotEquals()" will only throw is both the unexpected and actual are actually equal. It (correctly) does not throw a NoSuchElementException, which the test failure that the kata taker has to fix.

2019-10-13 13:48 UTC, c-guntur requested changes
Added a few in-line comments. Please review. Happy to discuss further.

2019-10-13 13:58 UTC, c-guntur commented on .gitignore
> +.settings
NIce !

2019-10-19 16:04 UTC, faisal6621 commented
Hi @c-guntur 
I had made the necessary changes as requested.

2019-11-10 14:57 UTC, c-guntur commented
Apologies for the delay in merging this. Will review today.

2019-11-10 15:02 UTC, merged